TARGET := bp
CFLAGS := -Iinc -DINPUT_SIZE=INPUT_SIZE_SMALL
LDFLAGS := -lm -lrt

CLEANMETOO += snr.txt small_kernel3_output.bin

RUNARGS := inout

ACCEPT_DIR ?= /sampa/share/accept/accept

include $(ACCEPT_DIR)/accept.mk
