TARGET := 2d_convolution
CFLAGS := -Iinc -DINPUT_SIZE=INPUT_SIZE_LARGE
LDFLAGS := -lm -lrt

CLEANMETOO += 2dconv_output.0.mat

ACCEPT_DIR ?= /sampa/share/accept/accept

include $(ACCEPT_DIR)/accept.mk
