ARCH    := msp430
SOURCES := msp430-strawman.c

RUNSHIM = $(ACCEPTDIR)/plat/msp430/run.sh

ACCEPT_DIR := ../../accept
include $(ACCEPT_DIR)/../accept-apps/plat/msp430.mk
include $(ACCEPT_DIR)/accept.mk
